### ISSUE TITLE
could you give me prepared data

### ISSUE THREAD

**Issue by torotocat** [kinredon/Harmonious-Teacher#20]
Can you provide me with prepared data? Thank you very much!

**Comment by torotocat** [comment]
Can you provide me with prepared data? Thank you very much!

**Comment by kinredon** [comment]
We have no right to distribute the datasets, you can download the dataset following the instructions from [dataset preparation](https://github.com/kinredon/Harmonious-Teacher?tab=readme-ov-file#dataset), the dataset can be easily downloaded from the official websites.
