### ISSUE TITLE
Run the model on coco dataset?

### ISSUE THREAD

**Issue by x2-peng** [kinredon/Harmonious-Teacher#5]
Thank you for your attribution.
I tried to run Harmonious-Teacher on coco dataset since the baseline Denseteacher is analyzed on coco. But by simply changing the dataset from Cityscapes to coco,the experiment result is even lower than Denseteacher by almost 5%
I change the code serveral times but dosen't seem to work, I want to know whether you train the model on coco and its performance.

**Comment by kinredon** [comment]
@Under-graduate Hi, thanks for your interest!

I have not trained the HT model on COCO before. 

Although our code is based on DenseTeacher, the architecture of FCOS in HT differs from that in DenseTeacher. In particular, FCOS in DenseTeacher is the improved FCOS while ours is the original FCOS with an IoU Branch. The improved FCOS will bring significant performance improvement. We chose the base version of FCOS following previous cross-domain object detection works for a relatively fair comparison.

If I remember correctly, the main differences between the base and improved versions can be roughly as follows:
base v.s. improved
1. Centerness branches and IoU branches
2. The different places for the centerness/iou branches (classification head or regression head).
3. Positive sample definition. 

Please compare the difference in the model config of FCOS between ours and DenseTeacher.
https://github.com/kinredon/Harmonious-Teacher/blob/863eda2d4fc2ced8fee228034033865e54ddc286/ht_c2f/config.py#L22C11-L22C11

If you have any problems or have some results, feel free to update the information in this issue.
