### ISSUE TITLE
annotation file of bdd100k dataset

### ISSUE THREAD

**Issue by thkimYonsei** [kinredon/Harmonious-Teacher#7]
First of all, thank you for your code and kind explanations to run it.
I'm trying to run experiment on cityscape to bdd100k, but I found that there exist two detection annotation files in bdd100k.
Which one of the two files ("Labels" vs "Detection 2020 Labels" in https://bdd-data.berkeley.edu/portal.html#download) did you use as annotation of bdd100k?
I hope you can help me with this.
Thank you

**Comment by kinredon** [comment]
Hi @thkimYonsei, sorry for the delayed reply. I downloaded the bdd100k dataset a long time ago. If you are still needed, feel free to send me an email, and I will upload it to the google drive.

**Comment by kevinLin36699** [comment]
I would like the dataset file for BDD100K. Could you please send it to me？

**Comment by kinredon** [comment]
Feel free to contact me via email.
