### ISSUE TITLE
About the CITY dataset

### ISSUE THREAD

**Issue by GingerCohle** [kinredon/Harmonious-Teacher#9]
Sorry, I can generate voc version of foggycity by get_multianno.py? Are you run based on python2.7 to generate? Or can you provide the voc folder with generated voc city?

**Comment by kinredon** [comment]
Yeah, you can generate the voc version of cityscapes/foggycityscapes by get_multianno.py. The cityscapes and foggycityscapes share the same labels. 

The difference between Python 2.7 and Python 3+ for the get_multianno.py is minor, just need a little modification for different Python versions.

If you need the generated voc cityscape, feel free to contact me via email.
